import "./globals.css";
import Navbar from "./components/Nav/Navbar";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import { dark } from "@clerk/themes";
import Toast from "./components/Utils/Toast";

export const metadata = {
  title: "Expense-Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          baseTheme: dark,
        }}
      >
        <body className="relative text-white bg-slate-900">
          <Navbar />
          {children}
          <Toast />
        </body>
      </ClerkProvider>
    </html>
  );
}
