import "./globals.css";
import Navbar from "./Navbar";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import { dark } from "@clerk/themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          baseTheme: dark,
        }}
      >
        <body className="text-white bg-slate-900">
          <Navbar />
          <main className="min-h-[calc(100vh-80px)] px-4 py-4 mx-auto max-w-[700px]">
            {children}
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
